version: '3.8'

services:
  chat_frontend:
    container_name: chat_frontend
    build:
      context: .
    env_file:
      - .env
    networks:
      - chat_frontend_network
    ports:
      - 3030:3030

networks:
  chat_frontend_network:
    driver: bridge
