services:
  chat-frontend:
    container_name: chat-frontend
    build:
      context: .
    env_file:
      - .env
    networks:
      - chat_frontend_network
    ports:
      - 3030:3030
networks:
  chat_frontend_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1420"

