version: '3.8'

services:
  express-app:
    build:
      context: .
      target: production  # Use the production stage for the final build
    ports:
      - 3030:3030
    env_file:
      - .env
    networks:
      - chat_server_network
    volumes:
      - .:/app  # Mount the current directory for development (optional)

networks:
  chat_server_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1420"
